# Generated by Django 5.2.5 on 2025-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='detalles',
            field=models.TextField(null=True),
        ),
    ]
